# src:https://github.com/Azure/kubernetes-keyvault-flexvol/blob/master/deployment/nginx-flex-kv-podidentity.yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-flex-kv-podid
    aadpodidbinding: kv
  name: nginx-flex-kv-podid
spec:
  containers:
  - name: nginx-flex-kv-podid
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /kvmnt
      readOnly: true
  volumes:
  - name: test
    flexVolume:
      driver: "azure/kv"
      options:
        usepodidentity: "true"         # [OPTIONAL] if not provided, will default to "false"
        keyvaultname: "keyvault-aks-2020"               # the name of the KeyVault
        keyvaultobjectnames: "DatabaseLogin;DatabasePassword"      # list of KeyVault object names (semi-colon separated)
        keyvaultobjecttypes: "secret;secret"    # list of KeyVault object types: secret, key or cert (semi-colon separated)
        keyvaultobjectversions: ""     # [OPTIONAL] list of KeyVault object versions (semi-colon separated), will get latest if empty
        resourcegroup: ""              # [REQUIRED FOR < v0.0.14] the resource group of the KeyVault
        subscriptionid: ""             # [REQUIRED FOR < v0.0.14] the subscription ID of the KeyVault
        tenantid: "<YOUR_AZURE_TENANT_ID>"                   # the tenant ID of the KeyVault